DROP DATABASE IF EXISTS horarios;
-- MySQL Script generated by MySQL Workbench
-- Sun May 17 14:56:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema horarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema horarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horarios` DEFAULT CHARACTER SET utf8 ;
USE `horarios` ;

-- -----------------------------------------------------
-- Table `horarios`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`periodos` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`programas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`programas` (
  `id_programa` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `id_periodo` INT NOT NULL,
  PRIMARY KEY (`id_programa`, `id_periodo`),
  INDEX `fk_programas_periodos1_idx` (`id_periodo` ) ,
  CONSTRAINT `fk_programas_periodos1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `horarios`.`periodos` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`jornadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`jornadas` (
  `id_jornada` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_jornada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`dias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`dias` (
  `id_dia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`materia` (
  `id_materia` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `creditos` INT NOT NULL,
  `semestre` VARCHAR(45) NULL,
  `id_programa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_materia`, `id_programa`),
  INDEX `fk_materia_programas_idx` (`id_programa` ) ,
  CONSTRAINT `fk_materia_programas`
    FOREIGN KEY (`id_programa`)
    REFERENCES `horarios`.`programas` (`id_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`nrcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`nrcs` (
  `id_nrcs` INT NOT NULL AUTO_INCREMENT,
  `id_materia` VARCHAR(20) NOT NULL,
  `id_programa` VARCHAR(20) NOT NULL,
  `id_jornada` INT NOT NULL,
  PRIMARY KEY (`id_nrcs`, `id_materia`, `id_programa`, `id_jornada`),
  INDEX `fk_nrcs_materia1_idx` (`id_materia` , `id_programa` ) ,
  INDEX `fk_nrcs_jornadas1_idx` (`id_jornada` ) ,
  CONSTRAINT `fk_nrcs_materia1`
    FOREIGN KEY (`id_materia` , `id_programa`)
    REFERENCES `horarios`.`materia` (`id_materia` , `id_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nrcs_jornadas1`
    FOREIGN KEY (`id_jornada`)
    REFERENCES `horarios`.`jornadas` (`id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`clases` (
  `id_dia` INT NOT NULL,
  `id_nrc` INT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  PRIMARY KEY (`id_dia`, `id_nrc`),
  INDEX `fk_dias_has_nrcs_nrcs1_idx` (`id_nrc` ) ,
  INDEX `fk_dias_has_nrcs_dias1_idx` (`id_dia` ) ,
  CONSTRAINT `fk_dias_has_nrcs_dias1`
    FOREIGN KEY (`id_dia`)
    REFERENCES `horarios`.`dias` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_has_nrcs_nrcs1`
    FOREIGN KEY (`id_nrc`)
    REFERENCES `horarios`.`nrcs` (`id_nrcs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
